export const products = [
  {
    id: 1,
    title: "Purina excellent Adult Maintenance",
    price: 14000,
    stock: 3,
    description: "Alimento balanceado Adult Maintenance 20kg",
    category: "alimentoySnacks",
    img: "https://res.cloudinary.com/dtgaqvham/image/upload/v1686883267/alimentoB_xionbq.png",
  },
  {
    id: 2,
    title: "Osspret Shampoo cachorros",
    price: 2300,
    stock: 3,
    description: "Shampoo antiséptico ph controlado cachorros",
    category: "higiene",
    img: "https://res.cloudinary.com/dtgaqvham/image/upload/v1689160658/image_lvble6.png",
  },
  {
    id: 3,
    title: "Can Hueso",
    price: 4300,
    stock: 2,
    description: "antistress toy",
    category: "juguetes",
    img: "https://res.cloudinary.com/dtgaqvham/image/upload/v1686885824/huesitojuguet_duiycx.png",
  },
  {
    id: 4,
    title: "Bravecto",
    price: 5700,
    stock: 1,
    description: "Antipulgas y antigarrapaticida perros 2 a 5kg",
    category: "pulguisidas",
    img: "https://res.cloudinary.com/dtgaqvham/image/upload/v1686885335/antipulgaygarrapata_kx20ge.jpg",
  },
];
